server:
  port: 8181

---

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**