#spring:
#    profiles:
#      group:
#          "local": testdb
#
#---

spring:
#    activate:
#        on-profile: testdb
    datasource:
      url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true
      username: root
      password: test

    batch:
      job:
        enabled: true
        name: ${job.name:NONE}
