server:
  port: 8081
---
spring:
  application:
    name: member-service

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka #Eureka Server 정보